In [12]:
import numpy as np

In [7]:
np_array = np.array([[1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]])

np_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
np_array[ np_array>10 ]

array([11, 12, 13, 14, 15])

In [11]:
np_array[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [12]:
import pandas as pd
friends = pd.Series(['Pankaj','Onxang','Nishal'],index=['Australia','Japan','Kathmandu'])
friends

Australia    Pankaj
Japan        Onxang
Kathmandu    Nishal
dtype: object

In [14]:
friends['Japan']
type(friends)

pandas.core.series.Series

In [16]:
friends[0]

/var/folders/r7/smw89w9s6qs_9p119sl_kphr0000gn/T/ipykernel_63047/4154782090.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  friends[0]


'Pankaj'

In [17]:
friends.values

array(['Pankaj', 'Onxang', 'Nishal'], dtype=object)

In [24]:
mates = pd.DataFrame({"name":['Pankaj','Onxang','Nishal'],
                        "last_name":['Meche','Limbu','Thapa'],
                        "city":["Sydney","Tokyo","Kathmandu"]},index=['Australia','Japan','Kathmandu'])

In [25]:
mates

,name,last_name,city
Australia,Pankaj,Meche,Sydney
Japan,Onxang,Limbu,Tokyo
Kathmandu,Nishal,Thapa,Kathmandu


In [28]:
mates.loc["Australia":"Japan"] # retrieving via lables, rows by loc is inclusive to end points

,name,last_name,city
Australia,Pankaj,Meche,Sydney
Japan,Onxang,Limbu,Tokyo


In [29]:
mates.iloc[0:2] # retireving via position, see iloc is exclusive to the  endpoints

,name,last_name,city
Australia,Pankaj,Meche,Sydney
Japan,Onxang,Limbu,Tokyo


In [22]:
mates["city"]

0       Sydney
1        Tokyo
2    Kathmandu
Name: city, dtype: object

In [30]:
mates.to_csv("mates.csv",index=False)

In [31]:
test_df = pd.read_csv("mates.csv")
test_df

,name,last_name,city
0,Pankaj,Meche,Sydney
1,Onxang,Limbu,Tokyo
2,Nishal,Thapa,Kathmandu


In [24]:
from pandas import DataFrame
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)
X= wine.data
y = wine.target
y

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64

In [25]:
X.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000


In [28]:
X['hue'].count()

np.int64(178)

In [ ]:
X['hue'].corr(X['nonflavanoid_phenols']) # checking correlation bw columns

np.float64(-0.26263963114983346)

In [37]:
both = X.assign(target=y)
both

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2


In [38]:
both.groupby('target')["malic_acid"].mean()

target
0    2.010678
1    1.932676
2    3.333750
Name: malic_acid, dtype: float64

In [46]:
both.groupby('target')["malic_acid"].agg(['mean','std','count'])

,mean,std,count
target,,,
0,2.010678,0.688549,59
1,1.932676,1.015569,71
2,3.333750,1.087906,48


In [49]:
both.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [89]:
import numpy as np
num1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n1 = num1.reshape(6,2).copy()
num1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
n1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [98]:
num2 = np.array([11,12,13,14,15,16,17,18,19,20,21,22])
len(num2)
n2 = num2.reshape(6,2).copy()
num2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [ ]:
num1 + num2


array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2])

In [99]:
n2.reshape(6,2)

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22]])

In [100]:
n1 + n2

array([[12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [103]:
np.concatenate([num1,num2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22])

In [104]:
np.concatenate([n1,n2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22]])

In [106]:
np.vstack([num1,num2])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]])

In [107]:
np.vstack([n1,n2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22]])

In [108]:
np.hstack([n1,n2])

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20],
       [11, 12, 21, 22]])

In [109]:
np.hstack([num1,num2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22])

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
iris = load_iris(as_frame=True)
# here i have loaded the iris dataset which is built-in in scikit learn
X = iris.data
y = iris.target
train_X,val_X,train_y,val_y = train_test_split(X,y,random_state=1)
model= Perceptron(random_state=1)

#  fitting the model
model.fit(train_X,train_y)

val_predictions = model.predict(val_X)
mse = mean_squared_error(val_y, val_predictions)
mse

0.15789473684210525