In [1]:
print(4 * 8)

32


In [3]:
print("hello world");
list1 = [11,2,32,4,5,6,7]
c=list1.pop(2)
print(c)
list1

hello world
32


[11, 2, 4, 5, 6, 7]

In [5]:
list1.sort()
print(list1)

[2, 4, 5, 6, 7, 11]


In [6]:
list1.reverse()
print(list1)

[11, 7, 6, 5, 4, 2]


In [84]:
list1

[1, 2, 4, 5, 6, 7]

In [ ]:
x = ["prabin", "samir"]
x.insert(1,"king")


['prabin', 'king', 'samir']

In [32]:
x.reverse()

In [33]:
x

['samir', 'king', 'prabin']

In [34]:
x.index('prabin')

2

In [9]:
student = {"nme": "prabin","age":"43","marks":"O"}
student['nme']

'prabin'

In [38]:
student["stream"]="datascience"

In [39]:
student

{'name': 'prabin', 'age': '43', 'marks': 'O', 'stream': 'datascience'}

In [49]:
print(student.keys())

print(student.values())
print(student.items())

dict_keys(['name', 'age', 'marks', 'stream'])
dict_values(['prabin', '43', 'O', 'datascience'])
dict_items([('name', 'prabin'), ('age', '43'), ('marks', 'O'), ('stream', 'datascience')])


In [10]:
print(student.get("name","N/A"))

N/A


In [57]:
score1 = [98,87,76,43,32,13,78]
score2 = []
for x in score1:
    #q = x**2
    score2.append(x*2)
score2
    

[196, 174, 152, 86, 64, 26, 156]

In [60]:
score3 = [x*3 for x in score1]
score3

[294, 261, 228, 129, 96, 39, 234]

In [61]:
student

{'name': 'prabin', 'age': '43', 'marks': 'O', 'stream': 'datascience'}

In [62]:
student.pop("stream")

'datascience'

In [63]:
student

{'name': 'prabin', 'age': '43', 'marks': 'O'}

In [ ]:
words = ['apple','ball','cat','dog','elephant'] #list ma iterate gareko ho
for word in words:
    print(word)

apple
ball
cat
dog
elephant


In [ ]:
#dict ma iterate garekoo ho
fruits = {'apple':'250','banana':'60','pear':'300',"orange":"200"}
for fruit,price in fruits.items():
    print(f'the current price of {fruit} is {price}')

the current price of apple is 250
the current price of banana is 60
the current price of pear is 300
the current price of orange is 200


In [ ]:
# this is dict comprehension
test = {fruit: int(price)*2 for fruit,price in fruits.items()}
test

{'apple': 500, 'banana': 120, 'pear': 600, 'orange': 400}

In [18]:
#dict comprehension with conditionals
pricing = {'claude':200,'grok':100,"chatgpt":150,'deepseek':25}
test3 ={model:price*2 for model,price in pricing.items() if price<=100}
test3
test4 ={model:price-30 for model,price in pricing.items()if model == 'claude' or model == 'chatgpt'}
test4

{'claude': 170, 'chatgpt': 120}

In [22]:
employee = [{"name":"sam","designation": "manager", "age":34},
            {"10thmarks":{"math":23,"chemistry":34,"social":124,"english":54,"french":43,"geography":23}},
            {"12thmarks":{"math":58,"chemistry":90,"physics":89}}
            ]

In [23]:
print(employee[2]["12thmarks"]["physics"])

89


In [26]:
employee[1]["10thmarks"].values()
# [23, 34, 124, 54, 43, 23]

dict_values([23, 34, 124, 54, 43, 23])

In [104]:
employee = [
    {"name": "sam", "designation": "manager", "age": 34},
    {"10thmarks": {"math": 23, "physics": 34, "chemistry": 124, "biology": 54, "english": 43, "hindi": 23}},
    {"family": {"wife": "rose", "sons": {"eldest": "ronk", "youngest": "david"}}, "neighbour": "rosy"}
]

employee[1]["10thmarks"]["physics"]   # 34
employee[2]["family"]["sons"]["youngest"]

'david'

In [1]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
len(a)

5

In [35]:
xoop = "pluto is a planet"

In [46]:
xoop.startswith('pluto')
xoop.endswith('net')

True

In [47]:
dob = '2005/01/10'
year,month,day = dob.split('/')

In [53]:
type(year)
year

'2005'

In [2]:
import math
'this is a math module, it is of tyoe {}'.format(type(math))

"this is a math module, it is of tyoe <class 'module'>"

In [3]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.9/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in 

In [6]:
math.exp(2)
math.exp

<function math.exp(x, /)>

In [5]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [ ]:
print("value of pi to 4 significant digits = {:.4}".format(math.pi))

value of pi to 4 significant digits = 3.142


In [39]:
import numpy 
dice_rolls = numpy.random.randint(low=1,high=6,size=20)
dice_rolls

array([2, 1, 4, 1, 4, 5, 3, 4, 1, 3, 4, 4, 1, 2, 3, 4, 2, 3, 5, 5])

In [40]:
dice_rolls.sum()

np.int64(61)

In [42]:
dice_rolls >= 3

array([False, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True])

In [46]:
ylist= [[1,2,3],[4,5,6],[7,8,9]]
arr = numpy.asarray(ylist)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#indexing a single element of a matrix in numpy
arr[2,-1]
arr[1,2]

np.int64(6)

In [ ]:
#indexing a list of lists in python
ylist[1][2]

6

In [54]:
#slicing in python
arr[1,0:2]

array([4, 5])

In [56]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [57]:
arr[-1,-1]

np.int64(9)

In [62]:
sub = arr[0:2]
sub

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
sub[0][2] = 87

In [65]:
arr

array([[ 1,  2, 87],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [66]:
arr[arr>4]

array([87,  5,  6,  7,  8,  9])