### This covers the implementation of numpy coursework.
 It is intended as a practice material as well experimentation playground  with the objectives of learning and applying numpy.

In [ ]:
# numpy contains only one data structure i.e nd-array 
# creating a numpy nd-array but lets import numpy first 
import numpy as np
list1 = [1,3,5,7,9] # we send a list in to np.array() to crate 1-Dimensional numpy array
arr1 = np.array([list1]) # we can also directly pass the list ,  arr1 = np.array([1,3,5,7,9])
arr1



array([[1, 3, 5, 7, 9]])

In [ ]:
arr1.dtype # we can check the data type of elements of a numpy array

dtype('int64')

In [26]:
# we can create a matrix(2 dimensional array), passing a list of lists in numpy array
arr2 = np.array([[1,3,5],[7,9,11],[13,15,17]])
print(arr2)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [31]:
arr2.shape # gives the shape of the nd array

(3, 3)

In [ ]:
arr2.size # total no of elements in a nd array,also a product of nd-array's shape 

9

In [33]:
arr2.itemsize # it tells us the size of single element of a numpy array in bytes

8

In [49]:
arr3_float = np.array([4.1,5.2,6.3])
print(arr3_float.dtype)
arr3_int = arr3_float.astype('int') # astype() is used to change numpy array to a specified data type
print(arr3_int.dtype)

float64
int64


In [38]:
arr4 = np.array([[[10,20,30],[40,50,60]],[[1,2,3],[4,5,6]]]) # this is a three dimensional nd array 
# the nd dimensionals are realted and closely reflects tensors we studied.
arr4

array([[[10, 20, 30],
        [40, 50, 60]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [ ]:
arr4.shape # this is a 3 Dimensional Tensor

(2, 2, 3)

In [ ]:
arr5 = np.zeros((3,4)) # gives a zero matrix or nd array of shape given by tuple passed.
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((4,3)) # same as np.zeros , it just sets all elements to one
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr7 = np.identity(4) # gives a identity matix of order 4. we pass order as a argument.
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])